#theme: jekyll-theme-merlot

# https://github.com/jekyll/minima/tree/master/_layouts
theme: minima

#fancier
# https://github.com/mmistakes/minimal-mistakes

title: Power Mode - Zeranthium
description: IntelliJ Plugin to Get Into The Zone

#pages:
#  - about.md

header_pages:
  - test.hml
#  - about.md

disqus:
    shortname: disqus_FCVoWPUQuI

#
google_analytics: UA-96436087-3

show_excerpts: true           

# https://pages.github.com/versions/
gems:
  - jekyll-octicons

