name: Build


#on:
#  workflow_dispatch

on:
  push:
    branches:
      test_actions_branch

jobs:

#  build-for-ui-test-mac-os:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup Java
#        uses: actions/setup-java@v3
#        with:
#          distribution: zulu
#          java-version: 11
#      - name: Setup FFmpeg
#        uses: FedericoCarboni/setup-ffmpeg@v1
#        with:
#          # Not strictly necessary, but it may prevent rate limit
#          # errors especially on GitHub-hosted macos machines.
#          token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Clean
#        run: gradle :clean
#
#      - name: Run Idea
#        run: |
#          mkdir -p ui-test-example/build/reports
#          gradle :runIdeForUiTests > ui-test-example/build/reports/idea.log &
#
#      - name: Wait for Idea started
#        uses: jtalk/url-health-check-action@v2
#        with:
#          url: http://127.0.0.1:8082
#          max-attempts: 15
#          retry-delay: 30s
#
#      - name: Tests
#        run: gradle :test
#
#      - name: Tests Ide
#        env:
#          TEST_TYPE: UI
#        run: |
#          TEST_TYPE=UI ./gradlew :test --info --tests "com.cschar.pmode3.uitest.OpenSettingsJavaTest.opens_project"
#
#      - name: Move video
#        if: ${{ failure() }}
#        run: mv ./video ui-test-example/build/reports
#
#      - name: Save fails report
#        if: ${{ failure() }}
#        uses: actions/upload-artifact@v3
#        with:
#          name: ui-test-fails-report-mac
#          path: |
#            ui-test-example/build/reports
#
  build-for-ui-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean
        run: gradle :clean

      - name: Run Idea
        run: start gradlew.bat :runIdeForUiTests

      - name: Wait for Idea started
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: http://localhost:8082
          max-attempts: 15
          retry-delay: 30s

      - name: Tests
        run: gradle :test

      - name: Tests IDE
        env:
          TEST_TYPE: UI
        run: |
          ./gradlew :test --info --tests "com.cschar.pmode3.uitest.OpenSettingsJavaTest.opens_project"

      - name: Move video
        if: ${{ failure() }}
        run: mv ./video ui-test-example/build/reports

      - name: Save fails report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-fails-report-windows
          path: |
            ui-test-example/build/reports
